#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_LISTVIEW 101

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_REBAR 102
#define IDC_TOOLBAR 103
#define IDC_SEARCH 104
#define IDC_LISTVIEW 105
#define IDC_STATUSBAR 106

// Main Menu
#define IDM_SETTINGS 107
#define IDM_RUNASADMIN 108
#define IDM_SAVE_HTML 109
#define IDM_EXIT 110
#define IDM_FIND 111
#define IDM_SHOW_UPDATES 112
#define IDM_SHOW_SYSTEM_COMPONENTS 113
#define IDM_REFRESH 114
#define IDM_ALWAYSONTOP_CHK 115
#define IDM_DARKMODE_CHK 116
#define IDM_SKIPUACWARNING_CHK 117
#define IDM_CHECKUPDATES_CHK 118
#define IDM_WEBSITE 119
#define IDM_CHECKUPDATES 120
#define IDM_DONATE 121
#define IDM_ABOUT 122

// Listview Menu
#define IDM_OPEN 123
#define IDM_EXPLORE 124
#define IDM_COPY 125
#define IDM_COPY_VALUE 126
#define IDM_UNINSTALL 127
#define IDM_DELETE 128

#define IDM_SELECT_ALL 129
#define IDM_ZOOM 130

#define IDX_LANGUAGE 1000

// Strings
#define IDS_FILE 1
#define IDS_VIEW 2
#define IDS_SETTINGS 3
#define IDS_HELP 4
#define IDS_FIND 5
#define IDS_SAVE_HTML 6
#define IDS_EXIT 7
#define IDS_LANGUAGE 8
#define IDS_RUNASADMIN 9
#define IDS_SHOW_UPDATES 10
#define IDS_SHOW_SYSTEM_COMPONENTS 11
#define IDS_REFRESH 12
#define IDS_WEBSITE 13
#define IDS_CHECKUPDATES 14
#define IDS_DONATE 15
#define IDS_ABOUT 16
#define IDS_NAME 17
#define IDS_VERSION 18
#define IDS_TIMESTAMP 19
#define IDS_INSTALLER 20
#define IDS_STATUS_TOTAL 21
#define IDS_COPY 22
#define IDS_COPY_VALUE 23
#define IDS_SELECT_ALL 24
#define IDS_OPEN 25
#define IDS_EXPLORE 26
#define IDS_UNINSTALL 27
#define IDS_DELETE 28
#define IDS_ALWAYSONTOP_CHK 29
#define IDS_DARKMODE_CHK 30
#define IDS_LOADONSTARTUP_CHK 31
#define IDS_AUTOSIZECOLUMNS_CHK 32
#define IDS_SKIPUACWARNING_CHK 33
#define IDS_CHECKUPDATES_CHK 34
#define IDS_QUESTION_DELETE 35
#define IDS_PROPERTIES 36
#define IDS_RESET 37
#define IDS_COMMENT 38

// PNG
#define IDP_SEARCH_LIGHT 100
#define IDP_SEARCH_DARK 101
#define IDP_DELETE 102
#define IDP_REFRESH 103
#define IDP_DONATE 104

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
