#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_LISTVIEW 101

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_LISTVIEW 102
#define IDC_STATUSBAR 103

// Main Menu
#define IDM_SETTINGS 104
#define IDM_EXIT 105
#define IDM_FIND 106
#define IDM_SHOW_UPDATES 107
#define IDM_SHOW_SYSTEM_COMPONENTS 108
#define IDM_REFRESH 109
#define IDM_ALWAYSONTOP_CHK 110
#define IDM_DARKMODE_CHK 111
#define IDM_SKIPUACWARNING_CHK 112
#define IDM_CHECKUPDATES_CHK 113
#define IDM_WEBSITE 114
#define IDM_CHECKUPDATES 115
#define IDM_DONATE 116
#define IDM_ABOUT 117

// Listview Menu
#define IDM_OPEN 118
#define IDM_EXPLORE 119
#define IDM_COPY 120
#define IDM_DELETE 121

#define IDM_SELECT_ALL 122
#define IDM_ZOOM 123

#define IDX_LANGUAGE 1000

// Strings
#define IDS_FILE 1
#define IDS_VIEW 2
#define IDS_SETTINGS 3
#define IDS_HELP 4
#define IDS_EXIT 5
#define IDS_LANGUAGE 6
#define IDS_SHOW_UPDATES 7
#define IDS_SHOW_SYSTEM_COMPONENTS 8
#define IDS_REFRESH 9
#define IDS_WEBSITE 10
#define IDS_CHECKUPDATES 11
#define IDS_DONATE 12
#define IDS_ABOUT 13
#define IDS_NAME 14
#define IDS_VERSION 15
#define IDS_TIMESTAMP 16
#define IDS_INSTALLER 17
#define IDS_STATUS_TOTAL 18
#define IDS_COPY 19
#define IDS_SELECT_ALL 20
#define IDS_OPEN 21
#define IDS_EXPLORE 22
#define IDS_DELETE 23
#define IDS_ALWAYSONTOP_CHK 24
#define IDS_DARKMODE_CHK 25
#define IDS_LOADONSTARTUP_CHK 26
#define IDS_AUTOSIZECOLUMNS_CHK 27
#define IDS_SKIPUACWARNING_CHK 28
#define IDS_CHECKUPDATES_CHK 29
#define IDS_QUESTION_DELETE 30
#define IDS_PROPERTIES 31
#define IDS_RESET 32
#define IDS_COMMENT 33

// Icons
#define IDI_MAIN 100
#define IDI_ACTIVE IDI_MAIN
#define IDI_INACTIVE 101

#endif // __RESOURCE_H__
