#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_LISTVIEW 101

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_REBAR 102
#define IDC_TOOLBAR 103
#define IDC_SEARCH 104
#define IDC_LISTVIEW 105
#define IDC_STATUSBAR 106

// Main Menu
#define IDM_SETTINGS 107
#define IDM_RUNASADMIN 108
#define IDM_EXIT 109
#define IDM_FIND 110
#define IDM_SHOW_UPDATES 111
#define IDM_SHOW_SYSTEM_COMPONENTS 112
#define IDM_REFRESH 113
#define IDM_ALWAYSONTOP_CHK 114
#define IDM_DARKMODE_CHK 115
#define IDM_SKIPUACWARNING_CHK 116
#define IDM_CHECKUPDATES_CHK 117
#define IDM_WEBSITE 118
#define IDM_CHECKUPDATES 119
#define IDM_DONATE 120
#define IDM_ABOUT 121

// Listview Menu
#define IDM_OPEN 122
#define IDM_EXPLORE 123
#define IDM_COPY 124
#define IDM_UNINSTALL 125
#define IDM_DELETE 126

#define IDM_SELECT_ALL 127
#define IDM_ZOOM 128

#define IDX_LANGUAGE 1000

// Strings
#define IDS_FILE 1
#define IDS_VIEW 2
#define IDS_SETTINGS 3
#define IDS_HELP 4
#define IDS_FIND 5
#define IDS_EXIT 6
#define IDS_LANGUAGE 7
#define IDS_RUNASADMIN 8
#define IDS_SHOW_UPDATES 9
#define IDS_SHOW_SYSTEM_COMPONENTS 10
#define IDS_REFRESH 11
#define IDS_WEBSITE 12
#define IDS_CHECKUPDATES 13
#define IDS_DONATE 14
#define IDS_ABOUT 15
#define IDS_NAME 16
#define IDS_VERSION 17
#define IDS_TIMESTAMP 18
#define IDS_INSTALLER 19
#define IDS_STATUS_TOTAL 20
#define IDS_COPY 21
#define IDS_SELECT_ALL 22
#define IDS_OPEN 23
#define IDS_EXPLORE 24
#define IDS_UNINSTALL 25
#define IDS_DELETE 26
#define IDS_ALWAYSONTOP_CHK 27
#define IDS_DARKMODE_CHK 28
#define IDS_LOADONSTARTUP_CHK 29
#define IDS_AUTOSIZECOLUMNS_CHK 30
#define IDS_SKIPUACWARNING_CHK 31
#define IDS_CHECKUPDATES_CHK 32
#define IDS_QUESTION_DELETE 33
#define IDS_PROPERTIES 34
#define IDS_RESET 35
#define IDS_COMMENT 36

// PNG
#define IDP_SEARCH_LIGHT 100
#define IDP_SEARCH_DARK 101
#define IDP_DELETE 102
#define IDP_REFRESH 103
#define IDP_DONATE 104

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
